POST http://localhost:3000/api/sinahq

{
  "code": ["sh000688", "sh601933"]
}

###

POST http://localhost:3000/api/sinasg

{
  "code": "金龙"
}

###

GET http://api.ly01.ml:3030/logto_auth_hello
Authorization: eyJhbGciOiJFUzM4NCIsInR5cCI6IkpXVCIsImtpZCI6ImNwZ2VUR3VHLS05T1BzdldSNWxYRWxrSW9XcnBTUFFCNUxxc3ZoLXVSSUkifQ.eyJzdWIiOiJwc2w4cXZwajY0NzQiLCJuYW1lIjpudWxsLCJwaWN0dXJlIjpudWxsLCJ1c2VybmFtZSI6InBwY2xlYW4iLCJhdF9oYXNoIjoiYzd4UXdIV3hFNXNqOWdOSUlBTW1hR2R4WTczQnVxYU8iLCJhdWQiOiJlenYzNmlwZDJoZWM5YzJ3NzhtdjYiLCJleHAiOjE2ODkzMTczNTgsImlhdCI6MTY4OTMxMzc1OCwiaXNzIjoiaHR0cHM6Ly9hdXRoLjgweWVzLm1sL29pZGMifQ.XqJa4bJo1wgkEfAU5g2HaPAu40vYQkQ-q9Xp5Qjg3s-gvMSwN6CQK4K0jVMziv6R-luDfNwCG311OOWOIM7fvnZo4_rU4IROQGYPJzt7K8oyHHN5xF8nQdW_CvdLw4gQ